name: Docker Image CI
on:
  push:
    branches:
      - dev
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v1
      - name: Print greeting
        env:
          TARGET: world
        run: |
          echo "Hello, $TARGET!"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag centos-7-perl:$(date +%s)
      - name: Say goodbye
        env:
          TARGET: world
        run: |
          echo "Goodbye, $TARGET!"
